In [1]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.model_selection import cross_val_score
df=pd.read_csv("heart.csv")
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [2]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [3]:
df.sex.unique()

array([1, 0])

In [4]:
df.target.unique()

array([1, 0])

In [5]:
df.shape

(303, 14)

In [6]:
cond1=df["target"]==0
df[cond1]

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
165   67    1   0       160   286    0        0      108      1      1.5   
166   67    1   0       120   229    0        0      129      1      2.6   
167   62    0   0       140   268    0        0      160      0      3.6   
168   63    1   0       130   254    0        0      147      0      1.4   
169   53    1   0       140   203    1        0      155      1      3.1   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
165      1   3     2       0  
166      1   2     3       0  
167      0   2     2       0  
168      1   1     3       0  
169      0   0     3       0  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[138 rows x 14 columns]

In [7]:
cond2=df["target"]==1
df[cond2]

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
160   56    1   1       120   240    0        1      169      0      0.0   
161   55    0   1       132   342    0        1      166      0      1.2   
162   41    1   1       120   157    0        1      182      0      0.0   
163   38    1   2       138   175    0        1      173      0      0.0   
164   38    1   2       138   175    0        1      173      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
160      0   0     2       1  
161      2   0     2       1  
162      2   0     2       1  
163      2   4     2       1  
164      2   4     2       1  

[165 rows x 14 columns]

In [8]:
df.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [9]:
x=df.drop("target",axis="columns").values
x

array([[63.,  1.,  3., ...,  0.,  0.,  1.],
       [37.,  1.,  2., ...,  0.,  0.,  2.],
       [41.,  0.,  1., ...,  2.,  0.,  2.],
       ...,
       [68.,  1.,  0., ...,  1.,  2.,  3.],
       [57.,  1.,  0., ...,  1.,  1.,  3.],
       [57.,  0.,  1., ...,  1.,  1.,  2.]], shape=(303, 13))

In [10]:
y=df["target"].values
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [11]:
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2,random_state=0)
X_train

array([[43.,  0.,  2., ...,  1.,  0.,  2.],
       [66.,  0.,  2., ...,  1.,  1.,  2.],
       [58.,  1.,  2., ...,  2.,  0.,  2.],
       ...,
       [56.,  1.,  3., ...,  1.,  0.,  3.],
       [47.,  1.,  2., ...,  2.,  0.,  2.],
       [58.,  1.,  1., ...,  1.,  0.,  2.]], shape=(242, 13))

In [12]:
import numpy as np
np.set_printoptions(suppress=True)
X_test

array([[ 70. ,   1. ,   0. , 145. , 174. ,   0. ,   1. , 125. ,   1. ,
          2.6,   0. ,   0. ,   3. ],
       [ 64. ,   1. ,   3. , 170. , 227. ,   0. ,   0. , 155. ,   0. ,
          0.6,   1. ,   0. ,   3. ],
       [ 59. ,   1. ,   3. , 170. , 288. ,   0. ,   0. , 159. ,   0. ,
          0.2,   1. ,   0. ,   3. ],
       [ 60. ,   1. ,   0. , 125. , 258. ,   0. ,   0. , 141. ,   1. ,
          2.8,   1. ,   1. ,   3. ],
       [ 62. ,   1. ,   2. , 130. , 231. ,   0. ,   1. , 146. ,   0. ,
          1.8,   1. ,   3. ,   3. ],
       [ 48. ,   1. ,   0. , 124. , 274. ,   0. ,   0. , 166. ,   0. ,
          0.5,   1. ,   0. ,   3. ],
       [ 40. ,   1. ,   0. , 110. , 167. ,   0. ,   0. , 114. ,   1. ,
          2. ,   1. ,   0. ,   3. ],
       [ 63. ,   1. ,   0. , 130. , 254. ,   0. ,   0. , 147. ,   0. ,
          1.4,   1. ,   1. ,   3. ],
       [ 56. ,   0. ,   0. , 200. , 288. ,   1. ,   0. , 133. ,   1. ,
          4. ,   0. ,   2. ,   3. ],
       [ 63. ,   1. ,   0. ,

In [13]:
Y_train

array([1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0])

In [14]:
Y_test

array([0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1])

In [15]:
model=LogisticRegression(solver="lbfgs",max_iter=2000)
model.fit(X_train,Y_train)
print(model.predict(X_test))

[0 1 1 0 0 0 0 0 0 0 1 1 0 1 1 1 0 1 0 1 1 0 0 0 1 1 0 0 1 1 1 0 1 1 1 1 0
 1 0 0 1 1 0 0 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1]


In [16]:
print(model.score(X_test,Y_test)*100)

85.24590163934425


In [17]:
print(model.predict([[38,1,2,138,175,0,1,173,0,0.0,2,4,2]]))

[0]


In [18]:
print(X_test[1:10])
print(model.predict(X_test[1:10]))

[[ 64.    1.    3.  170.  227.    0.    0.  155.    0.    0.6   1.    0.
    3. ]
 [ 59.    1.    3.  170.  288.    0.    0.  159.    0.    0.2   1.    0.
    3. ]
 [ 60.    1.    0.  125.  258.    0.    0.  141.    1.    2.8   1.    1.
    3. ]
 [ 62.    1.    2.  130.  231.    0.    1.  146.    0.    1.8   1.    3.
    3. ]
 [ 48.    1.    0.  124.  274.    0.    0.  166.    0.    0.5   1.    0.
    3. ]
 [ 40.    1.    0.  110.  167.    0.    0.  114.    1.    2.    1.    0.
    3. ]
 [ 63.    1.    0.  130.  254.    0.    0.  147.    0.    1.4   1.    1.
    3. ]
 [ 56.    0.    0.  200.  288.    1.    0.  133.    1.    4.    0.    2.
    3. ]
 [ 63.    1.    0.  130.  330.    1.    0.  132.    1.    1.8   2.    3.
    3. ]]
[1 1 0 0 0 0 0 0 0]


In [19]:
final=cross_val_score(model,x,y,cv=5)
final

array([0.80327869, 0.86885246, 0.85245902, 0.86666667, 0.75      ])

In [20]:
final.mean()

np.float64(0.8282513661202187)

In [50]:
import pandas as pd
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import Lasso
df=pd.read_csv("Drug.csv")
df

Age Sex      BP Cholesterol        Na         K   Drug
0     23   F    HIGH        HIGH  0.792535  0.031258  drugY
1     47   M     LOW        HIGH  0.739309  0.056468  drugC
2     47   M     LOW        HIGH  0.697269  0.068944  drugC
3     28   F  NORMAL        HIGH  0.563682  0.072289  drugX
4     61   F     LOW        HIGH  0.559294  0.030998  drugY
..   ...  ..     ...         ...       ...       ...    ...
195   56   F     LOW        HIGH  0.848774  0.073380  drugC
196   16   M     LOW        HIGH  0.743021  0.061886  drugC
197   52   M  NORMAL        HIGH  0.549945  0.055581  drugX
198   23   M  NORMAL      NORMAL  0.784520  0.055959  drugX
199   40   F     LOW      NORMAL  0.683503  0.060226  drugX

[200 rows x 7 columns]

In [51]:
df.Drug.unique()

array(['drugY', 'drugC', 'drugX', 'drugA', 'drugB'], dtype=object)

In [52]:
df.Age.unique()

array([23, 47, 28, 61, 22, 49, 41, 60, 43, 34, 74, 50, 16, 69, 32, 57, 63,
       48, 33, 31, 39, 45, 18, 65, 53, 46, 15, 73, 58, 66, 37, 68, 67, 62,
       24, 26, 40, 38, 29, 17, 54, 70, 36, 19, 64, 59, 51, 42, 56, 20, 72,
       35, 52, 55, 30, 21, 25])

In [53]:
dummies=pd.get_dummies(df[["Sex","BP","Cholesterol"]],dtype="int64")
dummies

Sex_F  Sex_M  BP_HIGH  BP_LOW  BP_NORMAL  Cholesterol_HIGH  \
0        1      0        1       0          0                 1   
1        0      1        0       1          0                 1   
2        0      1        0       1          0                 1   
3        1      0        0       0          1                 1   
4        1      0        0       1          0                 1   
..     ...    ...      ...     ...        ...               ...   
195      1      0        0       1          0                 1   
196      0      1        0       1          0                 1   
197      0      1        0       0          1                 1   
198      0      1        0       0          1                 0   
199      1      0        0       1          0                 0   

     Cholesterol_NORMAL  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0  
..                  ...  
195                   0  
196                   0  
197                   0  
198                   1  
199                   1  

[200 rows x 7 columns]

In [54]:
final=pd.concat([df,dummies],axis="columns")
final

Age Sex      BP Cholesterol        Na         K   Drug  Sex_F  Sex_M  \
0     23   F    HIGH        HIGH  0.792535  0.031258  drugY      1      0   
1     47   M     LOW        HIGH  0.739309  0.056468  drugC      0      1   
2     47   M     LOW        HIGH  0.697269  0.068944  drugC      0      1   
3     28   F  NORMAL        HIGH  0.563682  0.072289  drugX      1      0   
4     61   F     LOW        HIGH  0.559294  0.030998  drugY      1      0   
..   ...  ..     ...         ...       ...       ...    ...    ...    ...   
195   56   F     LOW        HIGH  0.848774  0.073380  drugC      1      0   
196   16   M     LOW        HIGH  0.743021  0.061886  drugC      0      1   
197   52   M  NORMAL        HIGH  0.549945  0.055581  drugX      0      1   
198   23   M  NORMAL      NORMAL  0.784520  0.055959  drugX      0      1   
199   40   F     LOW      NORMAL  0.683503  0.060226  drugX      1      0   

     BP_HIGH  BP_LOW  BP_NORMAL  Cholesterol_HIGH  Cholesterol_NORMAL  
0          1       0          0                 1                   0  
1          0       1          0                 1                   0  
2          0       1          0                 1                   0  
3          0       0          1                 1                   0  
4          0       1          0                 1                   0  
..       ...     ...        ...               ...                 ...  
195        0       1          0                 1                   0  
196        0       1          0                 1                   0  
197        0       0          1                 1                   0  
198        0       0          1                 0                   1  
199        0       1          0                 0                   1  

[200 rows x 14 columns]

In [55]:
final.drop(columns=["Sex","BP","Cholesterol"],axis=1,inplace=True)
final

Age        Na         K   Drug  Sex_F  Sex_M  BP_HIGH  BP_LOW  BP_NORMAL  \
0     23  0.792535  0.031258  drugY      1      0        1       0          0   
1     47  0.739309  0.056468  drugC      0      1        0       1          0   
2     47  0.697269  0.068944  drugC      0      1        0       1          0   
3     28  0.563682  0.072289  drugX      1      0        0       0          1   
4     61  0.559294  0.030998  drugY      1      0        0       1          0   
..   ...       ...       ...    ...    ...    ...      ...     ...        ...   
195   56  0.848774  0.073380  drugC      1      0        0       1          0   
196   16  0.743021  0.061886  drugC      0      1        0       1          0   
197   52  0.549945  0.055581  drugX      0      1        0       0          1   
198   23  0.784520  0.055959  drugX      0      1        0       0          1   
199   40  0.683503  0.060226  drugX      1      0        0       1          0   

     Cholesterol_HIGH  Cholesterol_NORMAL  
0                   1                   0  
1                   1                   0  
2                   1                   0  
3                   1                   0  
4                   1                   0  
..                ...                 ...  
195                 1                   0  
196                 1                   0  
197                 1                   0  
198                 0                   1  
199                 0                   1  

[200 rows x 11 columns]

In [56]:
final.drop(columns=["Sex_F","Cholesterol_NORMAL"],axis=1,inplace=True)
final

Age        Na         K   Drug  Sex_M  BP_HIGH  BP_LOW  BP_NORMAL  \
0     23  0.792535  0.031258  drugY      0        1       0          0   
1     47  0.739309  0.056468  drugC      1        0       1          0   
2     47  0.697269  0.068944  drugC      1        0       1          0   
3     28  0.563682  0.072289  drugX      0        0       0          1   
4     61  0.559294  0.030998  drugY      0        0       1          0   
..   ...       ...       ...    ...    ...      ...     ...        ...   
195   56  0.848774  0.073380  drugC      0        0       1          0   
196   16  0.743021  0.061886  drugC      1        0       1          0   
197   52  0.549945  0.055581  drugX      1        0       0          1   
198   23  0.784520  0.055959  drugX      1        0       0          1   
199   40  0.683503  0.060226  drugX      0        0       1          0   

     Cholesterol_HIGH  
0                   1  
1                   1  
2                   1  
3                   1  
4                   1  
..                ...  
195                 1  
196                 1  
197                 1  
198                 0  
199                 0  

[200 rows x 9 columns]

In [57]:
import warnings
warnings.filterwarnings("ignore")

obj=LabelEncoder()
final["Drug"]=obj.fit_transform(final[["Drug"]])
final

Age        Na         K  Drug  Sex_M  BP_HIGH  BP_LOW  BP_NORMAL  \
0     23  0.792535  0.031258     4      0        1       0          0   
1     47  0.739309  0.056468     2      1        0       1          0   
2     47  0.697269  0.068944     2      1        0       1          0   
3     28  0.563682  0.072289     3      0        0       0          1   
4     61  0.559294  0.030998     4      0        0       1          0   
..   ...       ...       ...   ...    ...      ...     ...        ...   
195   56  0.848774  0.073380     2      0        0       1          0   
196   16  0.743021  0.061886     2      1        0       1          0   
197   52  0.549945  0.055581     3      1        0       0          1   
198   23  0.784520  0.055959     3      1        0       0          1   
199   40  0.683503  0.060226     3      0        0       1          0   

     Cholesterol_HIGH  
0                   1  
1                   1  
2                   1  
3                   1  
4                   1  
..                ...  
195                 1  
196                 1  
197                 1  
198                 0  
199                 0  

[200 rows x 9 columns]

In [58]:
new_columns=["Age","Na","K","Sex_M","BP_HIGH","BP_LOW","BP_NORMAL","Cholesterol_HIGH","Drug"]
final=final[new_columns]
final

Age        Na         K  Sex_M  BP_HIGH  BP_LOW  BP_NORMAL  \
0     23  0.792535  0.031258      0        1       0          0   
1     47  0.739309  0.056468      1        0       1          0   
2     47  0.697269  0.068944      1        0       1          0   
3     28  0.563682  0.072289      0        0       0          1   
4     61  0.559294  0.030998      0        0       1          0   
..   ...       ...       ...    ...      ...     ...        ...   
195   56  0.848774  0.073380      0        0       1          0   
196   16  0.743021  0.061886      1        0       1          0   
197   52  0.549945  0.055581      1        0       0          1   
198   23  0.784520  0.055959      1        0       0          1   
199   40  0.683503  0.060226      0        0       1          0   

     Cholesterol_HIGH  Drug  
0                   1     4  
1                   1     2  
2                   1     2  
3                   1     3  
4                   1     4  
..                ...   ...  
195                 1     2  
196                 1     2  
197                 1     3  
198                 0     3  
199                 0     3  

[200 rows x 9 columns]

In [59]:
x=final.drop("Drug",axis="columns").values
x

array([[23.      ,  0.792535,  0.031258, ...,  0.      ,  0.      ,
         1.      ],
       [47.      ,  0.739309,  0.056468, ...,  1.      ,  0.      ,
         1.      ],
       [47.      ,  0.697269,  0.068944, ...,  1.      ,  0.      ,
         1.      ],
       ...,
       [52.      ,  0.549945,  0.055581, ...,  0.      ,  1.      ,
         1.      ],
       [23.      ,  0.78452 ,  0.055959, ...,  0.      ,  1.      ,
         0.      ],
       [40.      ,  0.683503,  0.060226, ...,  1.      ,  0.      ,
         0.      ]], shape=(200, 8))

In [60]:
y=final.Drug.values
y

array([4, 2, 2, 3, 4, 3, 4, 2, 4, 4, 2, 4, 4, 4, 3, 4, 3, 0, 2, 4, 4, 4,
       4, 4, 4, 4, 4, 3, 4, 4, 3, 1, 3, 4, 3, 3, 0, 3, 3, 3, 4, 1, 4, 3,
       3, 3, 0, 2, 4, 4, 4, 3, 4, 4, 1, 2, 1, 4, 3, 4, 4, 0, 4, 3, 1, 4,
       0, 3, 4, 4, 1, 4, 3, 4, 4, 4, 0, 4, 0, 3, 1, 3, 2, 0, 2, 1, 3, 4,
       4, 4, 4, 4, 4, 4, 4, 3, 4, 4, 4, 4, 0, 0, 2, 3, 4, 3, 3, 4, 1, 4,
       0, 3, 3, 3, 3, 4, 3, 3, 0, 4, 4, 4, 4, 4, 1, 4, 4, 3, 4, 3, 4, 4,
       3, 4, 4, 3, 1, 0, 1, 3, 0, 4, 1, 4, 0, 3, 3, 0, 3, 2, 0, 1, 3, 3,
       4, 2, 0, 4, 2, 3, 3, 1, 3, 4, 4, 4, 4, 3, 4, 0, 3, 3, 4, 4, 0, 4,
       0, 4, 4, 4, 4, 3, 3, 4, 4, 4, 1, 0, 4, 4, 4, 0, 4, 2, 4, 2, 2, 3,
       3, 3])

In [61]:
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [62]:
Y_test

array([2, 3, 4, 4, 4, 3, 3, 3, 4, 3, 0, 4, 4, 4, 1, 2, 4, 4, 3, 4, 4, 3,
       3, 3, 4, 4, 4, 4, 4, 3, 3, 2, 0, 3, 4, 4, 3, 4, 0, 3])

In [63]:
print(model.predict(X_test))

[2 3 2 0 3 3 3 3 2 3 0 0 0 3 1 2 1 3 3 0 0 3 3 3 3 3 3 3 3 3 3 2 0 3 3 1 3
 2 0 3]


In [64]:
print(model.score(X_test,Y_test)*100)

52.5


In [65]:
print(model.predict([[40,0.683503,0.060226,0,0,1,0,0]]))

[3]


In [66]:
obj=LogisticRegression()
obj.fit(X_train,Y_train)
print(obj.predict(X_test))

[2 4 4 4 4 4 4 4 2 3 0 4 4 4 4 4 1 4 4 4 4 4 3 4 4 3 4 3 3 3 4 2 4 3 4 1 3
 4 4 3]


In [67]:
print(obj.predict(X_test))

[2 4 4 4 4 4 4 4 2 3 0 4 4 4 4 4 1 4 4 4 4 4 3 4 4 3 4 3 3 3 4 2 4 3 4 1 3
 4 4 3]


In [68]:
print(obj.score(X_test,Y_test)*100)

55.00000000000001


In [69]:
model=GaussianNB()
model.fit(X_train,Y_train)
print(model.predict(X_test))

[2 3 2 0 3 3 3 3 2 3 0 0 0 3 1 2 1 3 3 0 0 3 3 3 3 3 3 3 3 3 3 2 0 3 3 1 3
 2 0 3]


In [70]:
print(model.score(X_test,Y_test)*100)

52.5


In [73]:
model=Lasso(alpha=50,max_iter=100,tol=0.1)
model.fit(X_train,Y_train)
print(model.predict(X_test))

[2.80625 2.80625 2.80625 2.80625 2.80625 2.80625 2.80625 2.80625 2.80625
 2.80625 2.80625 2.80625 2.80625 2.80625 2.80625 2.80625 2.80625 2.80625
 2.80625 2.80625 2.80625 2.80625 2.80625 2.80625 2.80625 2.80625 2.80625
 2.80625 2.80625 2.80625 2.80625 2.80625 2.80625 2.80625 2.80625 2.80625
 2.80625 2.80625 2.80625 2.80625]


In [74]:
print(model.score(X_test,Y_test))

-0.07759546539379492
